[PyTorchLibrary](https://pytorch.org/)

In [2]:
import torch
import numpy as np
import time


cpu


### PYTORCH VS NUMPY


In [6]:
start_time = time.time()
#matrix operations;a
zeros = torch.zeros(1,1)
end_time=time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.4f}")

0.0010


In [10]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time_cpu = end_time - start_time
print(f"{elapsed_time_cpu:.8f}")


start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time_numpy = end_time - start_time
print(f"{elapsed_time_numpy:.8f}")

0.15697050
0.25132537


### Embeddings represent categorical variables as continuos vectors. Pytorch we use the nn.Embedding module

In [6]:
import torch 
import torch.nn as nn

# Define an embedding layer with vocabulary size 100 and embedding dimension 50
embedding = nn.Embedding(100, 50)

# Input tensor of size (batch_size, sequence_length)
input_tensor = torch.LongTensor([[1, 2, 3], [4, 5, 0]])

# Get embeddings for the input tensor
embeddings = embedding(input_tensor)
#print(embeddings)


### torch.stack is used to concatenate tensors along a new dimension. Essentially the tensors are stacked on a new dimension

In [9]:


# Create three tensors of size (3, 2)
t1 = torch.tensor([[1, 2], [3, 4], [5, 6]])
t2 = torch.tensor([[7, 8], [9, 10], [11, 12]])
t3 = torch.tensor([[13, 14], [15, 16], [17, 18]])

# Stack tensors along a new dimension (resulting tensor shape: (3, 3, 2))
stacked_tensor = torch.stack((t1, t2, t3))
#stacked_tensor


### The block below draws a random sample from a multinomial distribution
[Multinomial distribution](https://en.wikipedia.org/wiki/Multinomial_distribution)

In [11]:
# Define probabilities for a multinomial distribution
probabilities = torch.tensor([0.1, 0.2, 0.3, 0.4])

# Draw 5 samples from the multinomial distribution
samples = torch.multinomial(probabilities, 5, replacement=True)
samples

tensor([3, 2, 3, 3, 2])

### torch.tril returns the lower triangular of a matrix and torch.triu returns the upper portion or triangular of the matrix

In [14]:
import torch

# Create a 3x3 matrix
matrix = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Extract the lower triangular part of the matrix
lower_triangular = torch.tril(matrix)

# Extract the upper triangular part of the matrix
upper_triangular = torch.triu(matrix)

print(lower_triangular)
print(upper_triangular)


tensor([[1, 0, 0],
        [4, 5, 0],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [0, 5, 6],
        [0, 0, 9]])
